# -*- coding: utf-8 -*-
"""Lab04_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thureinmyoag/MMDT_T-PY102_Batch01/blob/main/submissions/PY102001004/Lab04_py.ipynb
"""

# -------------------------
# Do not change the below Code
# -------------------------
class TreeNode:
    def __init__(self, value: str, left = None, right = None):
        self.value = value
        self.left = left
        self.right = right

def preorder(root):
    if not root:
        return []
    return [root.value] + preorder(root.left) + preorder(root.right)

def inorder(root):
    if not root:
        return []
    return inorder(root.left) + [root.value] + inorder(root.right)

def postorder(root):
    if not root:
        return []
    return postorder(root.left) + postorder(root.right) + [root.value]

# -------------------------

# -------------------------
# Q1 — Build Submission Tree for submissions folder
# Visit our class homework submission repo.
# Look inside the "submissions" folder.
# Pick TWO folders: your folder and your friend's folder (choose with files).
#
# Notes:
# - Ignore any subfolders inside the chosen folders.
# - Only consider FILES inside each chosen folder (each filename becomes a node).
# - Tree structure should be:
#     submissions
#     ├── folder1
#     │   ├── fileA
#     │   └── fileB
#     └── folder2
#         ├── fileC
#         └── fileD
# -------------------------
import os
def build_submission_tree(base_path: str, folder1: str, folder2: str) -> TreeNode:

    def build_file_chain(folder_path):
        files = []

        # Read items in folder
        for item in os.listdir(folder_path):
            full_path = os.path.join(folder_path, item)

            # Only keep files
            if os.path.isfile(full_path):
                files.append(item)

        # Optional: sort for consistent output
        files.sort()

        if not files:
            return None

        # Build binary chain: first file = left, rest go right
        head = TreeNode(files[0])
        current = head

        for f in files[1:]:
            current.right = TreeNode(f)
            current = current.right

        return head

    # Root node
    root = TreeNode(base_path)

    # Folder 1
    f1_node = TreeNode(folder1)
    f1_node.left = build_file_chain(os.path.join(base_path, folder1))

    # Folder 2
    f2_node = TreeNode(folder2)
    f2_node.left = build_file_chain(os.path.join(base_path, folder2))

    # Attach folders to root
    root.left = f1_node
    root.right = f2_node

    return root

# -------------------------
# Q2 — Visit All Nodes Using Tree Traversal (Print Everything)
#
# Use the provided traversal function to visit ALL nodes in the tree,
# including:
#   1) the root node: "submissions"
#   2) the two folder nodes
#   3) all file nodes under each folder
#
# Notes:
# - The printing order depends on the traversal you use (preorder, BFS, etc.).
# - You must use the provided traversal function (do not manually recurse).
# - Print exactly the node.value for each visited node.
# -------------------------

def print_all_nodes(root: TreeNode) -> None:
    """
    Traverse the tree and print the value stored in EVERY node.
    root: the TreeNode returned from build_submission_tree
    """
    for value in preorder(root):
        print(value)
# -------------------------
# Q3 — Find All Python Files (.py)
#
# Write a function that traverses the tree and returns
# a list of all files ending with ".py".
#
# Notes:
# - Use traversal (do not manually access children).
# - Return a list of strings.
# - The function should NOT print — it should return the list.
# - Example return:
#     ["folderA/file1.py", "folderB/main.py"]
# -------------------------

def find_py_files(root: TreeNode) -> list[str]:
    """
    Traverse the tree and return a list of all '.py' files.
    root: the TreeNode returned from build_submission_tree
    """
    list_py = []  # initialize the list before the loop

    # Use the existing preorder traversal
    for value in preorder(root):
        if value.endswith(".py"):  # check file extension
            list_py.append(value)  # add to the list

    return list_py

