# -*- coding: utf-8 -*-
"""lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rjn6DIYmQLswQnZ8XGPPHyrI5RtHp5DG
"""

"""
Lab 03 — Hash Tables (4 Questions)

Rules:
- Do NOT use print() or input().
- Implement the functions exactly as named.
- You may use basic Python lists and dictionaries.
- Do NOT use any built-in hash table libraries except dict for Q1.

Questions:
Q1) Hash map usage
Q2) Hash table with chaining (conceptual simulation)
Q3) Linear probing simulation
Q4) Quadratic probing simulation
"""


# -------------------------
# Q1 — Hash Map
# -------------------------

def char_frequency(s: str) -> dict[str, int]:
    # TODO
    dict1 = {}
    for i in s:
      if i in dict1:
        new_val = dict1.get(i) + 1
        dict1[i] = new_val
      else:
        dict1[i] = 1
    return dict1


# -------------------------
# Q2 — Chaining (Collision Handling)
# -------------------------

def insert_chaining(table: list[list[int]], key: int, size: int) -> list[list[int]]:
    """
    Q2:
    Simulate inserting a key into a hash table using chaining.

    - table is a list of buckets (each bucket is a list).
    - hash function: key % size
    - Insert the key into the correct bucket.

    Example:
      table = [[], [], []]
      key = 5
      size = 3
      index = 5 % 3 = 2
      output = [[], [], [5]]
    """
    table_var= table
    key_var = key
    size_var = size
    var_index = key_var % size_var

    table[var_index].append(key_var)
    return table


# -------------------------
# Q3 — Linear Probing
# -------------------------

def insert_linear_probing(table: list[int | None], key: int) -> list[int | None]:
    """
    Q3:
    Simulate inserting a key into a hash table using linear probing.

    Rules:
    - hash function: key % len(table)
    - If a slot is occupied, move to the next index (circular).
    - Insert the key into the first empty (None) slot.

    Example:
      table = [None, 4, None, None]
      key = 8

      hash = 8 % 4 = 0
      slot 0 is empty → insert

      output = [8, 4, None, None]
    """
    n = len(table)
    hash = key % len(table)
    for __ in range(n):
      if table[hash] is None:
        table[hash] = key
        return table
      else:
        hash = (hash+1)%len(table)
    return table


# -------------------------
# Q4 — Quadratic Probing
# -------------------------

def insert_quadratic_probing(table: list[int | None], key: int) -> list[int | None]:
    """
    Q4:
    Simulate inserting a key into a hash table using quadratic probing.

    Rules:
    - hash function: key % len(table)
    - Probe sequence:
        (hash + i*i) % len(table), for i = 0, 1, 2, ...
    - Insert the key into the first empty (None) slot.

    Example:
      table = [None, 7, None, None]
      key = 11

      hash = 11 % 4 = 3
      i = 0 → index = 3
      slot 3 is empty → insert

      output = [None, 7, None, 11]
    """
    # TODO
    len_table = len(table)
    hash = key % len_table
    i = 1

    for __ in range(len_table):
      hash = (hash + i**2)%len_table

      if table[hash] is None:
        table[hash] = key
        return table
      else:
        i += 1
    return table

