# -*- coding: utf-8 -*-
"""lab03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIgGSP-ccFwcRWcdNtwvtT73OV3d0UYX

# Q1) Hash map usage
"""

def char_frequency(s:str)->dict[str,int]:
  hash_map={}
  for char in s:
    if char in hash_map:
        hash_map[char]+=1
    else:
        hash_map[char]=1
  return hash_map

"""# Q2) Chaining (Collision Handling)"""

def insert_chaining(table:list[list[int]],key:int,size:int)->list[list[int]]:
  index=key%size
  table[index].append(key)
  return table

"""# Q3) Linear Probing"""

def insert_linear_probing(table:list[int|None],key:int)->list[int|None]:
  size=len(table)
  index=key%size
  while table[index]is not None:
    index=(index+1)%size
  table[index]=key
  return table

"""# Q4) Quadratic Probing"""

def insert_quadratic_probing(table:list[int|None],key:int)->list[int|None]:
  size=len(table)
  initial_hash=key%size
  i=0
  while True:
    index=(initial_hash+i*i)%size
    if table[index] is None:
      table[index]=key
      return table
    i+=1