# -*- coding: utf-8 -*-
"""Lab 00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjKyW3ZYpPAe-Lwjv-UDVpRGeTu2UvQa
"""

def submission_check():
    return "PY102001033"
