# -*- coding: utf-8 -*-
"""lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCDxooptSL7-q8qPdzxGq8z2q8Molqn2

# Q1. is_balanced_parentheses (s: str)
"""

def is_balanced_parentheses(self, s: str) -> bool:
        pair_dict = {")": "(", "}": "{", "]": "["}
        stack_list = []

        for char in s:
            if char in "({[":
                stack_list.append(char)
            elif char in ")}]":
                if not stack_list or stack_list.pop() != pair_dict[char]:
                    return False
        return len(stack_list) == 0

"""# Q2. next_greater_to_right (nums: list[int])"""

def next_greater_to_right(nums: list[int]) -> list[int]:
  result=[-1]*len(nums)
  stack=[]

  for i in range(len(nums)-1,-1,-1):
    while stack and stack[-1]<=nums[i]:
      stack.pop()

    if stack:
      result[i]=stack[-1]

    stack.append(nums[i])

  return result

"""# Q3. first_non_repeating(stream: str)"""

def first_non_repeating(stream: str) -> str:
  q=deque()
  count={}
  result=""

  for char in stream:
    count[char]=count.get(char,0)+1
    q.append(char)

    while q and count[q[0]] > 1:
      q.popleft()

    if q:
      result+=q[0]
    else:
      result+="#"

  return result

"""# Q4. hot_potato(names: list[str], k: int)"""

def hot_potato(names: list[str], k: int) -> str:
  queue=deque(names)
  while len(queue)>1:
    for _ in range(k):
      queue.append(queue.popleft())

    queue.popleft()

  return queue[0]