# -*- coding: utf-8 -*-
"""lab04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zDRptb-N8-53KVkdH_q8hQJf8E4WAKl

# Q1
"""

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def build_submission_tree(base_path: str, py102001033: str,py102001034: str) -> TreeNode:
    submissions_node = TreeNode(base_path)

    py102001033 = TreeNode(py102001033)
    py102001034 = TreeNode(py102001034)

    submissions_node.left = py102001033
    submissions_node.right = py102001034

    lab00 = TreeNode("lab00.py")
    lab01 = TreeNode("lab01.py")
    lab02 = TreeNode("lab02.py")
    lab03 = TreeNode("lab03.py")

    py102001033.left = lab00
    py102001033.right = lab01
    lab01.right = lab02
    lab02.right = lab03

    lab00 = TreeNode("lab00.py")
    lab01 = TreeNode("lab01.py")
    lab02 = TreeNode("lab02.py")

    py102001034.left = lab00
    py102001034.right = lab01
    lab01.right = lab02

    return(submissions_node)

"""# Q2"""

class MMDTPy102:
    def __init__(self, name, children=None):
        self.name = name
        self.children = children if children is not None else []

base_path_node = MMDTPy102("submissions", [
    MMDTPy102("py102001033", [MMDTPy102("lab00"), MMDTPy102("lab01"), MMDTPy102("lab02"),MMDTPy102("lab03")]),
    MMDTPy102("py102001034", [MMDTPy102("lab00"), MMDTPy102("lab01"), MMDTPy102("lab02")]),
])

stack=[base_path_node]

def print_all_nodes(root: MMDTPy102) -> None:
  if not root:
    return

  stack = [root]
  while stack:
    current_node = stack.pop()
    print(current_node.name)

    for child in reversed(current_node.children):
      stack.append(child)
print_all_nodes(base_path_node)

"""# Q3"""

my_root = build_submission_tree("submissions", "py102001033", "py102001034")

py_files = []

class MMDTPy102:
    def __init__(self, name, children=None):
        self.name = name
        self.children = children if children is not None else []

base_path_node = MMDTPy102("submissions", [
    MMDTPy102("py102001033", [
        MMDTPy102("lab00.py"),
        MMDTPy102("lab01.py"),
        MMDTPy102("lab02.py")
    ]),
    MMDTPy102("py102001034", [
        MMDTPy102("lab00.py"),
        MMDTPy102("lab01.py")
    ]),
])

py_files = []

stack = [(base_path_node, base_path_node.name)]

while stack:
    node, current_path = stack.pop()

    if node.name.lower().endswith(".py"):
        py_files.append(current_path)

    for child in reversed(node.children):
        new_path = f"{current_path}/{child.name}"
        stack.append((child, new_path))

print(py_files)